# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: TonrySquare Internal.
email: Toby@tidalair.com
description: > # this means to ignore newlines until "baseurl:"
  This is where we keep vidoes, links, youtube sites, as well as pdfs for
  music, and any audio reecordings.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  ybotman

# Build settings
markdown: kramdown

collections:
  - services
  - musicpdf
